version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    
#commented due to firewall
#volumes:
#      - /app/node_modules
#      - .:/app